allowCompoundWords: true
dictionaries:
  - bash
  - cpp-compound-words
  - docker
  - en_US
  - en-gb
  - git
  - markdown
  - misc
  - npm
  - python
  - shellscript
  - softwareTerms
  - terraform
enableGlobDot: true
features:
  weighted-suggestions: true
globRoot: ${cwd}
ignorePaths:
  - .*ignore
  - .cspell.config.yml
  - .git
  - .github/CODE_OF_CONDUCT.*
  - .terraform.lock.hcl
  - .vscode/extensions.json
language: en,ja
useGitignore: true
version: "0.2"
words:
  - byobu
  - deprioritize
  - desync
  - desynced
  - esync
  - hyfetch
  - kito
  - kislyuk
  - kuron
  - kuroné
  - larstobi
  - lazyjj
  - libgl
  - ludeeus
  - msedit
  - nodm
  - nvenc
  - nyancat
  - ollama
  - qwen
  - resynced
  - toctou
  - undispositioned
  - unioned
  - unpushed
  - unreplied
  - unscored
  - unwaived
  - vaapi
  - vainfo
  - waivable
  - xkblayout
  - xkbmodel
  - xkboptions
  - xkbvariant
  - xorgxrdp
  - xrdp
  - xsel
  - xsession
  - yazi
