allowCompoundWords: true
cache:
  cacheFormat: universal
  cacheLocation: node_modules/.cache/cspell/.cspell.cache
  cacheStrategy: metadata
  useCache: true
dictionaries:
  - cpp
  - en_US
  - en-gb
  - fullstack
  - git
  - markdown
  - misc
  - shellscript
  - softwareTerms
  - bash
  - cpp-compound-words
  - docker
  - npm
  - python
  - terraform
enableGlobDot: true
features:
  weighted-suggestions: true
globRoot: ${cwd}
ignorePaths:
  - .*ignore
  - .git
  - .github/CODE_OF_CONDUCT.*
  - .vscode/extensions.json
  - pnpm-lock.yaml
  - .cspell.config.yml
  - .terraform.lock.hcl
language: en,ja
useGitignore: true
version: '0.2'
words:
  - desync
  - desynced
  - idd
  - isort
  - kito
  - Kiro
  - kuron
  - kurone
  - kuroné
  - ONNX
  - pylint
  - pytest
  - pyproject
  - qwen
  - TOCTOU
  - tsfile
  - undispositioned
  - unioned
  - unmigrated
  - unmirrored
  - unpushed
  - unreplied
  - unrouted
  - unscored
  - unwaived
  - Esync
  - minimizable
  - waivable
  - rollup
  - GHEC
  - GHES
  - WHATWG
  - dedup
  - deinitialized
  - deprioritize
  - dofork
  - ministral
  - nektos
  - nvmrc
  - remediations
  - vrchat
  - byobu
  - esync
  - ghec
  - ghes
  - hyfetch
  - kislyuk
  - larstobi
  - lazyjj
  - libgl
  - ludeeus
  - msedit
  - nodm
  - nvenc
  - nyancat
  - ollama
  - resynced
  - toctou
  - vaapi
  - vainfo
  - xkblayout
  - xkbmodel
  - xkboptions
  - xkbvariant
  - xorgxrdp
  - xrdp
  - xsel
  - xsession
  - yazi
