#cloud-config
keyboard:
  layout: jp
  model: jp106
locale: ja_JP.UTF-8
package_reboot_if_required: true
package_update: true
package_upgrade: true
packages:
  # Cryptography
  - gnupg
  - pinentry-curses

  # Development tools
  - build-essential
  - gcc

  # Download tools
  - ca-certificates
  - curl
  - httpie
  - wget

  # Hardware
  - keyboard-configuration

  # Locales
  - language-pack-ja

  # Package manager
  - apt-file
  - apt-transport-https
  - apt-utils
  - software-properties-common

  # SCM tools
  - git

  # Text converters
  - yq
timezone: Asia/Tokyo
write_files:
  - path: /etc/apt/preferences.d/999-hold-kernel.pref
    content: |
      Package: linux-generic*
      Pin: release a=*
      Pin-Priority: -1

      Package: linux-headers*
      Pin: release a=*
      Pin-Priority: -1

      Package: linux-image*
      Pin: release a=*
      Pin-Priority: -1

      Package: linux-modules*
      Pin: release a=*
      Pin-Priority: -1

      Package: linux-modules-extra*
      Pin: release a=*
      Pin-Priority: -1

      Package: linux-tools*
      Pin: release a=*
      Pin-Priority: -1

      Package: linux-virtual*
      Pin: release a=*
      Pin-Priority: -1
  - path: /etc/skel/.local/src/setup-ubuntu/.gitkeep
    content: ''
  - path: /etc/skel/.sudo_as_admin_successful
    content: ''
  - path: /usr/local/bin/setup-ubuntu
    permissions: '0755'
    content: |
      #!/bin/sh
      set -eu

      TAR='setup-ubuntu.tar'
      TARPATH="${HOME}/.local/src/${TAR}"
      DEPLOYED="${HOME}/.local/src/setup-ubuntu"

      if [ -f "${TARPATH}" ]
      then
        tar -xvf "${TARPATH}" -C "${DEPLOYED}"
        rm "${TARPATH}"
      fi

      if [ ! -e "${DEPLOYED}/setup" ]
      then
        echo "Error: ${DEPLOYED}/setup does not exist." >&2
        exit 1
      fi

      "${DEPLOYED}/setup"
