#!/bin/sh
# -*- mode: sh -*-
# vim: set ft=sh :

set -eu

rm -f setup-ubuntu.tar
if command -v terraform >/dev/null 2>&1
then
  terraform destroy -auto-approve || true
  multipass delete -p setup-ubuntu || true
fi
