# -*- mode: ruby -*-
# vim: set ft=ruby :

# Configuration
brew 'chezmoi'

# Database tools
brew 'task'

# Files management
brew 'fd'

# Remote
brew 'awscli'

# SCM tools
brew 'ghq'
brew 'gti'
brew 'jj'
brew 'lazygit'
brew 'lazyjj'

# TUI
brew 'zellij'
