# -*- mode: ruby -*-
# vim: set ft=ruby :

# Configuration
brew 'chezmoi'

# Database tools
brew 'task'

# Development
brew 'ast-grep'
brew 'cargo-binstall'
brew 'direnv'
brew 'deno'
brew 'mise'
brew 'python'
brew 'tree-sitter'

# Files management
brew 'fd'

# Generative AI
brew 'ollama'

# Package management
brew 'vrc-get'

# Remote
brew 'awscli'

# SCM tools
brew 'ghq'
brew 'gti'
brew 'jj'
brew 'lazygit'
brew 'lazyjj'

# Shell utilities
brew 'powershell'

# Texts editors
brew 'neovim'

# TUI
brew 'zellij'
